/*
  # Create modules table

  1. New Tables
    - `modules`
      - `id` (bigint, primary key)
      - `course_id` (bigint, foreign key to courses)
      - `title` (text)
      - `order_index` (integer)
      - `created_at` (timestamp)
      - `updated_at` (timestamp)

  2. Security
    - Enable RLS on `modules` table
    - Add policy for authenticated users to read modules
    - Add policy for admins to manage modules
*/

CREATE TABLE IF NOT EXISTS modules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id bigint REFERENCES courses(id) ON DELETE CASCADE NOT NULL,
  title text NOT NULL,
  order_index integer NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE modules ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view modules"
  ON modules
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Admins can manage modules"
  ON modules
  FOR ALL
  TO authenticated
  USING ((auth.jwt() ->> 'user_role'::text) = 'admin'::text)
  WITH CHECK ((auth.jwt() ->> 'user_role'::text) = 'admin'::text);

-- Create index for better performance
CREATE INDEX IF NOT EXISTS modules_course_id_idx ON modules(course_id);
CREATE INDEX IF NOT EXISTS modules_order_idx ON modules(course_id, order_index);