/*
  # Create worksheet_notes table

  1. New Tables
    - `worksheet_notes`
      - `id` (bigint, primary key)
      - `user_id` (uuid, foreign key to auth.users)
      - `lesson_id` (bigint, foreign key to lessons)
      - `notes` (text - user notes)
      - `created_at` (timestamp)
      - `updated_at` (timestamp)

  2. Security
    - Enable RLS on `worksheet_notes` table
    - Add policy for users to manage their own worksheet notes

  3. Constraints
    - Unique constraint on user_id and lesson_id
*/

CREATE TABLE IF NOT EXISTS worksheet_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  lesson_id bigint REFERENCES lessons(id) ON DELETE CASCADE NOT NULL,
  notes text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE (user_id, lesson_id)
);

ALTER TABLE worksheet_notes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage own worksheet notes"
  ON worksheet_notes
  FOR ALL
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS worksheet_notes_user_id_idx ON worksheet_notes(user_id);
CREATE INDEX IF NOT EXISTS worksheet_notes_lesson_id_idx ON worksheet_notes(lesson_id);