/*
  # Create lessons table

  1. New Tables
    - `lessons`
      - `id` (bigint, primary key)
      - `module_id` (bigint, foreign key to modules)
      - `title` (text)
      - `type` (text - lesson type: text, video, quiz, sandbox, worksheet)
      - `content` (text - lesson content)
      - `order_index` (integer)
      - `created_at` (timestamp)
      - `updated_at` (timestamp)

  2. Security
    - Enable RLS on `lessons` table
    - Add policy for authenticated users to read lessons
    - Add policy for admins to manage lessons
*/

CREATE TABLE IF NOT EXISTS lessons (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_id bigint REFERENCES modules(id) ON DELETE CASCADE NOT NULL,
  title text NOT NULL,
  type text NOT NULL DEFAULT 'text',
  content text,
  order_index integer NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE lessons ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view lessons"
  ON lessons
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Admins can manage lessons"
  ON lessons
  FOR ALL
  TO authenticated
  USING ((auth.jwt() ->> 'user_role'::text) = 'admin'::text)
  WITH CHECK ((auth.jwt() ->> 'user_role'::text) = 'admin'::text);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS lessons_module_id_idx ON lessons(module_id);
CREATE INDEX IF NOT EXISTS lessons_order_idx ON lessons(module_id, order_index);
CREATE INDEX IF NOT EXISTS lessons_type_idx ON lessons(type);