/*
  # Create quizzes table

  1. New Tables
    - `quizzes`
      - `id` (bigint, primary key)
      - `lesson_id` (bigint, foreign key to lessons)
      - `title` (text)
      - `created_at` (timestamp)
      - `updated_at` (timestamp)

  2. Security
    - Enable RLS on `quizzes` table
    - Add policy for authenticated users to read quizzes
    - Add policy for admins to manage quizzes
*/

CREATE TABLE IF NOT EXISTS quizzes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lesson_id bigint REFERENCES lessons(id) ON DELETE CASCADE NOT NULL,
  title text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE quizzes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view quizzes"
  ON quizzes
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Admins can manage quizzes"
  ON quizzes
  FOR ALL
  TO authenticated
  USING ((auth.jwt() ->> 'user_role'::text) = 'admin'::text)
  WITH CHECK ((auth.jwt() ->> 'user_role'::text) = 'admin'::text);

-- Create index for better performance
CREATE INDEX IF NOT EXISTS quizzes_lesson_id_idx ON quizzes(lesson_id);