/*
  # Create quiz_questions table

  1. New Tables
    - `quiz_questions`
      - `id` (bigint, primary key)
      - `quiz_id` (bigint, foreign key to quizzes)
      - `order_index` (integer)
      - `question` (text)
      - `choices` (text array)
      - `answer_index` (integer)
      - `created_at` (timestamp)
      - `updated_at` (timestamp)

  2. Security
    - Enable RLS on `quiz_questions` table
    - Add policy for authenticated users to read quiz questions
    - Add policy for admins to manage quiz questions
*/

CREATE TABLE IF NOT EXISTS quiz_questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id bigint REFERENCES quizzes(id) ON DELETE CASCADE NOT NULL,
  order_index integer NOT NULL,
  question text NOT NULL,
  choices text[] NOT NULL,
  answer_index integer NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE quiz_questions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view quiz questions"
  ON quiz_questions
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Admins can manage quiz questions"
  ON quiz_questions
  FOR ALL
  TO authenticated
  USING ((auth.jwt() ->> 'user_role'::text) = 'admin'::text)
  WITH CHECK ((auth.jwt() ->> 'user_role'::text) = 'admin'::text);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS quiz_questions_quiz_id_idx ON quiz_questions(quiz_id);
CREATE INDEX IF NOT EXISTS quiz_questions_order_idx ON quiz_questions(quiz_id, order_index);